package org.nanotek.model;

import java.util.function.Supplier;

/**
 * Represents a label or "vertex" about the graph generated by the problem.
 * 
 * @author jose.carlos.canova@gmail.com
 *
 */
public class Station implements Comparable<Station>{

	protected String stationLabel;
	
	public Station(String stationLabel) {
		super();
		this.stationLabel = stationLabel;
	}

	public String getStationLabel() {
		return stationLabel;
	}

	public void setStationLabel(String stationLabel) {
		this.stationLabel = stationLabel;
	}

	@Override
	public String toString() {
		return stationLabel;
	}
	
	public static <T extends Station> T nullStation() { 
		return (T) new Station("");
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((stationLabel == null) ? 0 : stationLabel.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Station other = (Station) obj;
		if (stationLabel == null) {
			if (other.stationLabel != null)
				return false;
		} else if (!stationLabel.equals(other.stationLabel))
			return false;
		return true;
	}

	
	//TODO: test the compare method to fix any problem with the "empty" station... 
	@Override
	public int compareTo(Station o) {
		return this.stationLabel.compareTo(o.getStationLabel());
	}
	
}
